services:
  # --- HUB INFRASTRUCTURE ---
  hub-mongo:
    image: mongo:7.0
    container_name: hub-mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=gateway_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  hub-redis:
    image: redis:7-alpine
    container_name: hub-redis
    command: >
      redis-server 
      --appendonly yes 
      --appendfsync everysec 
      --maxmemory-policy noeviction
    volumes:
      - hub_redis_data:/data
    ports:
      - "6379:6379"

  hub-server:
    build:
      context: ..                   # Points to the 'gate/' root directory
      dockerfile: deployments/hub.Dockerfile
    container_name: hub-server
    depends_on:
      - hub-redis
      - hub-mongo
    environment:
      - REDIS_ADDR=hub-redis:6379
      - MONGO_URI=mongodb://hub-mongo:27017
      - DB_NAME=gateway_db
      - CONFIG_FILE_PATH=/cmd/config.json
    ports:
      - "8080:8080"

  edge-server:
    build:
      context: ..
      dockerfile: deployments/edge.Dockerfile
    container_name: edge-server
    depends_on:
      - hub-server
      - hub-redis
    environment:
      - REDIS_ADDR=hub-redis:6379
      - HUB_ADDR=http://hub-server:8080
      - PORT=:8080
    ports:
      - "8081:8080"

  dashboard:
    build:
      context: ..
      dockerfile: deployments/dashboard.Dockerfile
    container_name: dashboard
    depends_on:
      - hub-redis
    environment:
      - REDIS_ADDR=hub-redis:6379
      - PORT=:8090
    ports:
      - "8090:8090"

volumes:
  hub_redis_data:
  mongo_data: