// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: api/proto/quota_lease.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuotaLeaseService_RequestQuotaLease_FullMethodName = "/gate.quota.v1.QuotaLeaseService/RequestQuotaLease"
)

// QuotaLeaseServiceClient is the client API for QuotaLeaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuotaLeaseServiceClient interface {
	RequestQuotaLease(ctx context.Context, in *QuotaLeaseRequest, opts ...grpc.CallOption) (*QuotaLeaseResponse, error)
}

type quotaLeaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuotaLeaseServiceClient(cc grpc.ClientConnInterface) QuotaLeaseServiceClient {
	return &quotaLeaseServiceClient{cc}
}

func (c *quotaLeaseServiceClient) RequestQuotaLease(ctx context.Context, in *QuotaLeaseRequest, opts ...grpc.CallOption) (*QuotaLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuotaLeaseResponse)
	err := c.cc.Invoke(ctx, QuotaLeaseService_RequestQuotaLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuotaLeaseServiceServer is the server API for QuotaLeaseService service.
// All implementations must embed UnimplementedQuotaLeaseServiceServer
// for forward compatibility.
type QuotaLeaseServiceServer interface {
	RequestQuotaLease(context.Context, *QuotaLeaseRequest) (*QuotaLeaseResponse, error)
	mustEmbedUnimplementedQuotaLeaseServiceServer()
}

// UnimplementedQuotaLeaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuotaLeaseServiceServer struct{}

func (UnimplementedQuotaLeaseServiceServer) RequestQuotaLease(context.Context, *QuotaLeaseRequest) (*QuotaLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestQuotaLease not implemented")
}
func (UnimplementedQuotaLeaseServiceServer) mustEmbedUnimplementedQuotaLeaseServiceServer() {}
func (UnimplementedQuotaLeaseServiceServer) testEmbeddedByValue()                           {}

// UnsafeQuotaLeaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuotaLeaseServiceServer will
// result in compilation errors.
type UnsafeQuotaLeaseServiceServer interface {
	mustEmbedUnimplementedQuotaLeaseServiceServer()
}

func RegisterQuotaLeaseServiceServer(s grpc.ServiceRegistrar, srv QuotaLeaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedQuotaLeaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuotaLeaseService_ServiceDesc, srv)
}

func _QuotaLeaseService_RequestQuotaLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuotaLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaLeaseServiceServer).RequestQuotaLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuotaLeaseService_RequestQuotaLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaLeaseServiceServer).RequestQuotaLease(ctx, req.(*QuotaLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuotaLeaseService_ServiceDesc is the grpc.ServiceDesc for QuotaLeaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuotaLeaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gate.quota.v1.QuotaLeaseService",
	HandlerType: (*QuotaLeaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestQuotaLease",
			Handler:    _QuotaLeaseService_RequestQuotaLease_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/quota_lease.proto",
}
