// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: api/proto/quota_lease.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuotaLeaseRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Prefix          string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	ServiceId       string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ApiKey          string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	RequestedTokens int64                  `protobuf:"varint,4,opt,name=requested_tokens,json=requestedTokens,proto3" json:"requested_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QuotaLeaseRequest) Reset() {
	*x = QuotaLeaseRequest{}
	mi := &file_api_proto_quota_lease_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaLeaseRequest) ProtoMessage() {}

func (x *QuotaLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_quota_lease_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaLeaseRequest.ProtoReflect.Descriptor instead.
func (*QuotaLeaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_quota_lease_proto_rawDescGZIP(), []int{0}
}

func (x *QuotaLeaseRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *QuotaLeaseRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *QuotaLeaseRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *QuotaLeaseRequest) GetRequestedTokens() int64 {
	if x != nil {
		return x.RequestedTokens
	}
	return 0
}

type QuotaLeaseResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GrantedTokens   int64                  `protobuf:"varint,1,opt,name=granted_tokens,json=grantedTokens,proto3" json:"granted_tokens,omitempty"`
	LeaseTtlSeconds int64                  `protobuf:"varint,2,opt,name=lease_ttl_seconds,json=leaseTtlSeconds,proto3" json:"lease_ttl_seconds,omitempty"`
	RemainingGlobal int64                  `protobuf:"varint,3,opt,name=remaining_global,json=remainingGlobal,proto3" json:"remaining_global,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QuotaLeaseResponse) Reset() {
	*x = QuotaLeaseResponse{}
	mi := &file_api_proto_quota_lease_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaLeaseResponse) ProtoMessage() {}

func (x *QuotaLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_quota_lease_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaLeaseResponse.ProtoReflect.Descriptor instead.
func (*QuotaLeaseResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_quota_lease_proto_rawDescGZIP(), []int{1}
}

func (x *QuotaLeaseResponse) GetGrantedTokens() int64 {
	if x != nil {
		return x.GrantedTokens
	}
	return 0
}

func (x *QuotaLeaseResponse) GetLeaseTtlSeconds() int64 {
	if x != nil {
		return x.LeaseTtlSeconds
	}
	return 0
}

func (x *QuotaLeaseResponse) GetRemainingGlobal() int64 {
	if x != nil {
		return x.RemainingGlobal
	}
	return 0
}

var File_api_proto_quota_lease_proto protoreflect.FileDescriptor

const file_api_proto_quota_lease_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/quota_lease.proto\x12\rgate.quota.v1\"\x8e\x01\n" +
	"\x11QuotaLeaseRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12)\n" +
	"\x10requested_tokens\x18\x04 \x01(\x03R\x0frequestedTokens\"\x92\x01\n" +
	"\x12QuotaLeaseResponse\x12%\n" +
	"\x0egranted_tokens\x18\x01 \x01(\x03R\rgrantedTokens\x12*\n" +
	"\x11lease_ttl_seconds\x18\x02 \x01(\x03R\x0fleaseTtlSeconds\x12)\n" +
	"\x10remaining_global\x18\x03 \x01(\x03R\x0fremainingGlobal2m\n" +
	"\x11QuotaLeaseService\x12X\n" +
	"\x11RequestQuotaLease\x12 .gate.quota.v1.QuotaLeaseRequest\x1a!.gate.quota.v1.QuotaLeaseResponseB%Z#gateway/packages/common/types;typesb\x06proto3"

var (
	file_api_proto_quota_lease_proto_rawDescOnce sync.Once
	file_api_proto_quota_lease_proto_rawDescData []byte
)

func file_api_proto_quota_lease_proto_rawDescGZIP() []byte {
	file_api_proto_quota_lease_proto_rawDescOnce.Do(func() {
		file_api_proto_quota_lease_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_quota_lease_proto_rawDesc), len(file_api_proto_quota_lease_proto_rawDesc)))
	})
	return file_api_proto_quota_lease_proto_rawDescData
}

var file_api_proto_quota_lease_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_quota_lease_proto_goTypes = []any{
	(*QuotaLeaseRequest)(nil),  // 0: gate.quota.v1.QuotaLeaseRequest
	(*QuotaLeaseResponse)(nil), // 1: gate.quota.v1.QuotaLeaseResponse
}
var file_api_proto_quota_lease_proto_depIdxs = []int32{
	0, // 0: gate.quota.v1.QuotaLeaseService.RequestQuotaLease:input_type -> gate.quota.v1.QuotaLeaseRequest
	1, // 1: gate.quota.v1.QuotaLeaseService.RequestQuotaLease:output_type -> gate.quota.v1.QuotaLeaseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_quota_lease_proto_init() }
func file_api_proto_quota_lease_proto_init() {
	if File_api_proto_quota_lease_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_quota_lease_proto_rawDesc), len(file_api_proto_quota_lease_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_quota_lease_proto_goTypes,
		DependencyIndexes: file_api_proto_quota_lease_proto_depIdxs,
		MessageInfos:      file_api_proto_quota_lease_proto_msgTypes,
	}.Build()
	File_api_proto_quota_lease_proto = out.File
	file_api_proto_quota_lease_proto_goTypes = nil
	file_api_proto_quota_lease_proto_depIdxs = nil
}
